# Import sqlite3 package
import sqlite3

# For presentation of output
from tabulate import tabulate

# Import output from the queries
from FlightManagementDB_queries import view_flights, view_pilotschedule, return_allairports, view_departureinformation
from FlightManagementDB_queries import view_arrivalinformation, return_allaircraft, return_allairportIDs, addnewFlight
from FlightManagementDB_queries import return_allFlightIDs, view_flights_byDepartureDay, view_flights_byAircraftID

# Open the database generated by the sql file
db = sqlite3.connect('FlightManagementDB.db')

# GET a cursor object
cursor = db.cursor()

# Run the Main Command Line in a continuous loop until the user selects the Exit Option.
# All Database Changes are rolled back at the Exit Option
def main_menu():
    while True:
        print("\nWelcome to the Flight Management Database")
        print("Please choose one of the following options:")
        print("1. Add a New Flight")
        print("2. View Flights by Criteria")
        print("3. Update Flight Information")
        print("4. Assign Pilot to Flight")
        print("5. View Pilot Schedule")
        print("6. View/Update Departure Information")
        print("7. View/Update Destination Information")
        print("8. Exit")

        choice = input("Select an option: ")

        if choice == '1': # Add a New Flight
            # Validation data sources
            
            all_FlightIDs = [row[0] for row in return_allFlightIDs(cursor)] # Need to convert tuples from sqlite3 into a list of strings
            all_airportIDs = [row[0] for row in return_allairportIDs(cursor)]
            all_aircraftIDs = [row[0] for row in return_allaircraft(cursor)]
            valid_statuses = {"Scheduled","Delayed","Cancelled","Pending"}
            valid_departureday = {"Monday", "Tuesday", "Wednesday","Thursday","Friday"}
            
            # Validate there are no duplicate Flight IDs added to the database
            while True:
                FlightID = input("Insert Flight ID (i.e. FL1010): ")
                if FlightID in all_FlightIDs:
                    print("Duplicate FlightID. Please enter a unique FlightID.")
                else:
                    break
            # Only allow valid flight statuses to be input by user
            while True:
                FlightStatus = input("Insert Flight Status (Scheduled/Delayed/Cancelled/Pending): ")
            
                if FlightStatus in valid_statuses:
                    break
                else:
                    print("Invalid status. Please enter one of: Scheduled, Delayed, Cancelled, Pending.")

            # Future improvement - to include validation on inputs for Time
            DepartureTime = input("Insert Departure Time (i.e. 08:00): ")
            ArrivalTime = input("Insert Arrival Time (i.e. 08:00): ")
            
            # Only allow valid departure days with the assumptions flights operate only on Monday - Fridays
            while True:
                departureDay = input("Insert departure day: ")
            
                if departureDay in valid_departureday:
                    break
                else:
                    print("Invalid departure day. Please enter one of: Monday, Tuesday, Wednesday, Thursday, Friday.")
            
            # Only allow valid Airport and Aircraft IDs to be input by user
            # Not yet option to add new Airport or Aircraft IDs
            while True:
                StartAirportID = input("Insert Departure Airport ID: ")

                if StartAirportID in all_airportIDs:
                    break
                else:
                    print("Invalid AirportID. Please input one of the following valid Airport IDs: ")
                    print(all_airportIDs)
            while True:
                EndAirportID = input("Insert Arrival Airport ID: ")

                if EndAirportID in all_airportIDs:
                    break
                else:
                    print("Invalid AirportID. Please input one of the following valid Airport IDs: ")
                    print(all_airportIDs)
            while True:
                AircraftID = input("Insert Aircraft ID: ")
                
                if AircraftID in all_aircraftIDs:
                    break
                else:
                    print("Invalid Aircraft ID. Please input one of the following valid Aircraft IDs: ")
                    print(all_aircraftIDs)

            # Add the new flight to the database and return the updated database so user can see the addition
            all_rows = addnewFlight(cursor,FlightID,FlightStatus,DepartureTime,ArrivalTime,departureDay, StartAirportID,EndAirportID,AircraftID)
            
            headers = ["FlightID", "FlightStatus", "DepartureTime", "ArrivalTime", "DepartureDay" "StartAirportID", "EndAirportID","AircraftID"]
            print("Full Flight List:")
            print(tabulate(all_rows, headers=headers, tablefmt="grid"))

        elif choice == '2': # View all flights
            while True:
                viewflightoptions = input("View all flights input 1.  View Flights by Departure Day input 2. View Flights by Aircraft ID input 3: ")

                if viewflightoptions == '1':
                    all_rows = view_flights(cursor)
                    
                elif viewflightoptions == '2':
                    viewByDepartureDay = input("Input departure day:")
                    all_rows = view_flights_byDepartureDay(cursor,viewByDepartureDay)
    
                    
                elif viewflightoptions == '3':
                    while True:
                        viewByAircraftID = input("Input AircraftID:")
                        all_aircraftIDs = [row[0] for row in return_allaircraft(cursor)]
                    
                        if viewByAircraftID in all_aircraftIDs:
                            all_rows = view_flights_byAircraftID(cursor,viewByAircraftID)
                            break
                        else:
                            print("Invalid Aircraft ID. Please input one of the following valid Aircraft IDs: ")
                            print(all_aircraftIDs)
                        
                    
                else:
                    print("Invalid option, please input 1, 2 or 3")
                    continue
                if all_rows:
                    headers = ["DepartureDay","FlightID","FlightStatus","AircraftID"]
                    print(tabulate(all_rows, headers=headers, tablefmt="grid"))
                    #for row in all_rows:
                        #print(row[0] + ' : ' + row[1])
                    break

                else:
                    print("No flights found for that selection")

                
            
        elif choice == '5': # View Pilot Schedule
            viewpilotID = input("Enter PilotID (i.e. PILOT001): ")
            rows = view_pilotschedule(cursor, viewpilotID)
            if not rows:
                print("No flights assigned for " + viewpilotID)
                return
    
            headers = ["FlightID","Departure Day", "Departure Time", "Arrival Time", "From", "To", "Status"]
            print("Pilot Schedule for " + viewpilotID + ":")
            print(tabulate(rows, headers=headers, tablefmt="grid"))
            

        elif choice == '6': # View Departure Information
            all_rows = return_allairports(cursor)
            print("List of all airport locations in the database:")
            for row in all_rows:
                print(row[0])
            
            departureairport = input("Select an airport from the list above:")
            rows = view_departureinformation(cursor, departureairport)
            if not rows:
                print("No flights departing from " + departureairport)
                return

            headers = ["AirportStatus", "FlightID", "FlightStatus","DepartureDay", "DepartureTime", "AircraftID", "Lead Pilot"]
            print("Departure information for " + departureairport + ":")
            print(tabulate(rows, headers=headers, tablefmt="grid"))
        
        elif choice == '7': # View Arrival Information
            all_rows = return_allairports(cursor)
            print("List of all airport locations in the database:")
            for row in all_rows:
                print(row[0])
            
            arrivalairport = input("Select an airport from the list above:")
            rows = view_arrivalinformation(cursor, arrivalairport)
            if not rows:
                print("No flights arriving into " + arrivalairport)
                return

            headers = ["AirportStatus", "FlightID", "FlightStatus", "DepartureDay", "ArrivalTime", "AircraftID", "Lead Pilot"]
            print("Arrival information for " + arrivalairport + ":")
            print(tabulate(rows, headers=headers, tablefmt="grid"))

        elif choice == '8': # Rollback all database changes and exit Flight Management Database
            print("Exiting Flight Management Database.")
            db.rollback
            db.close
            break

        else:
            print("Invalid option.  Please try again. ")

main_menu()
