# Import sqlite3 package
import sqlite3

from tabulate import tabulate

# Open the database generated by the sql file
db = sqlite3.connect('FlightManagementDB.db')

# GET a cursor object
cursor = db.cursor()

def main_menu():
    while True:
        print("\nWelcome to the Flight Management Database")
        print("Please choose one of the following options:")
        print("1. Add a New Flight")
        print("2. View Flights by Criteria")
        print("3. Update Flight Information")
        print("4. Assign Pilot to Flight")
        print("5. View Pilot Schedule")
        print("6. View/Update Departure Information")
        print("7. View/Update Destination Information")
        print("8. Exit")

        choice = input("Select an option: ")

        if choice == '2':
            view_flight()

        elif choice == '5':
            view_pilotschedule()

        elif choice == '6':
            view_departureinformation()
        
        elif choice == '7':
            view_arrivalinformation()

        elif choice == '8':
            print("Exiting Flight Management Database.")
            break

        else:
            print("Invalid option.  Please try again. ")

def view_flight():
    query = '''SELECT FlightID, FlightStatus FROM Flight'''
    cursor.execute(query)
    all_rows = cursor.fetchall()
    for row in all_rows:
        print(row[0] + ' : ' + row[1])

def view_pilotschedule():
    viewpilotID = input("Enter PilotID (i.e. PILOT001): ")

    query = '''
        SELECT 
            Flight.FlightID,
            Flight.DepartureTime,
            Flight.ArrivalTime,
            Flight.StartAirportID,
            Flight.EndAirportID,
            Flight.FlightStatus
        FROM Assigned
        JOIN Flight ON Assigned.FlightID = Flight.FlightID
        WHERE Assigned.PilotID = ?'''
    cursor.execute(query, (viewpilotID,))
    rows = cursor.fetchall()
    
    if not rows:
        print("No flights assigned for " + viewpilotID)
        return
    
    headers = ["FlightID", "Departure", "Arrival", "From", "To", "Status"]
    print("Pilot Schedule for " + viewpilotID + ":")
    print(tabulate(rows, headers=headers, tablefmt="grid"))

def view_departureinformation():
    query = '''SELECT AirportLocation FROM Airport'''
    cursor.execute(query)
    all_rows = cursor.fetchall()
    print("List of all airport locations in the database:")
    for row in all_rows:
        print(row[0])

    departureairport = input("Select an airport from the list above:")
    query = ''' SELECT
                Airport.AirportStatus,
                Flight.FlightID,
                Flight.FlightStatus,
                Flight.DepartureTime,
                Flight.AircraftID,
                Assigned.PilotID
                FROM Flight
                JOIN Airport
                    ON Flight.StartAirportID = Airport.AirportID
                LEFT JOIN Assigned
                    ON Assigned.FlightID = Flight.FlightID
                    AND Assigned.PilotRole = 'Lead'
                WHERE Airport.AirportLocation = ?'''
    cursor.execute(query, (departureairport,))
    rows = cursor.fetchall()

    if not rows:
        print("No flights departing from " + departureairport)
        return

    headers = ["AirportStatus", "FlightID", "FlightStatus", "DepartureTime", "AircraftID", "Lead Pilot"]
    print("Departure information for " + departureairport + ":")
    print(tabulate(rows, headers=headers, tablefmt="grid"))

def view_arrivalinformation():
    query = '''SELECT AirportLocation FROM Airport'''
    cursor.execute(query)
    all_rows = cursor.fetchall()
    print("List of all airport locations in the database:")
    for row in all_rows:
        print(row[0])

    arrivalairport = input("Select an airport from the list above:")
    query = ''' SELECT
                Airport.AirportStatus,
                Flight.FlightID,
                Flight.FlightStatus,
                Flight.ArrivalTime,
                Flight.AircraftID,
                Assigned.PilotID
                FROM Flight
                JOIN Airport
                    ON Flight.EndAirportID = Airport.AirportID
                LEFT JOIN Assigned
                    ON Assigned.FlightID = Flight.FlightID
                    AND Assigned.PilotRole = 'Lead'
                WHERE Airport.AirportLocation = ?'''
    cursor.execute(query, (arrivalairport,))
    rows = cursor.fetchall()

    if not rows:
        print("No flights arriving into " + arrivalairport)
        return

    headers = ["AirportStatus", "FlightID", "FlightStatus", "ArrivalTime", "AircraftID", "Lead Pilot"]
    print("Arrival information for " + arrivalairport + ":")
    print(tabulate(rows, headers=headers, tablefmt="grid"))

main_menu()
