# Import sqlite3 package
import sqlite3

# Open the database generated by the sql file
db = sqlite3.connect('FlightManagementDB.db')

# GET a cursor object
cursor = db.cursor()

def main_menu():
    
    print("\nWelcome to the Flight Management Database")
    print("Please choose one of the following options:")
    print("1. Add a New Flight")
    print("2. View Flights by Criteria")
    print("3. Update Flight Information")
    print("4. Assign Pilot to Flight")
    print("5. View Pilot Schedule")
    print("6. View/Update Departure Information")
    print("7. View/Update Destination Information")

    choice = input("Select an option: ")

def view_flight():
    cursor.execute('''SELECT FlightID, FlightStatus FROM Flight''')
    all_rows = cursor.fetchall()
    for row in all_rows:
        print(row)


main_menu()
view_flight()